version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - pg-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      postgres-db-network:
        ipv4_address: 192.168.100.253

  articles-app:
    container_name: medium-articles-api
    image: medium-articles-api:0.0.1
    ports:
      - "8080:8080"
    networks:
      postgres-db-network:
        ipv4_address: 192.168.100.10
    depends_on:
      - postgres

volumes:
  pg-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/postgres

networks:
  postgres-db-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1