spring:

  profiles:
    active: postgres

  datasource:

    # URL TO USE WHEN WORKING LOCALLY
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:

    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true