spring:

  application:
    name: medium-articles-api

  profiles:
    active: postgres

  # MASTER DB WRITES, UPDATES & DELETES
  datasource:
    #url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    url: jdbc:postgresql://localhost:5432/medium
    #username: ${DATABASE_USERNAME}
    username: postgres
    #password: ${DATABASE_PASSWORD}
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      #host: ${REDIS_HOST}
      host: localhost
      port: 6379