spring:

  application:
    name: medium-articles-api

  profiles:
    active: postgres

  # MASTER DB WRITES, UPDATES & DELETES
  datasource1:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  # REPLICA DB ONLY SELECTS
  datasource2:
    url: jdbc:postgresql://${REPLICA_HOST}:${REPLICA_PORT}/${REPLICA_NAME}
    username: ${REPLICA_USERNAME}
    password: ${REPLICA_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379